
CREATE TABLE IF NOT EXISTS users(
    id integer primary key generated by DEFAULT as identity,
    login text,
    password text,
    age integer,
    isDeleted boolean
);


INSERT INTO users VALUES (1, 'John', '123', 22, false); 
INSERT INTO users VALUES (2, 'Jane', '321', 23, false);